
font_family		CaskaydiaCove Nerd Font Mono
bold_font		true
italic_font		auto
bold_italic_font	auto
#font_size 		12.6



disable_ligatures	never


cursor_text_color	background
cursor_shape		beam
cursor_trail		1
#cursor_trail_color	none

#detect_url		yes
#url_color		#0087bd
#url_style		curly
#open_url_with		default
#underline_hyperlinks	hover


#active_border_color	#00ff00
#inactive_border_color	#cccccc

foreground		#e1dee9
#background 		#253d5b
background      #212D3D
background_opacity 0.75
background_blur		75

#background_image	/PATH/TO/IMAGE



###MAPS###

map ctrl+shift+k	scroll_page_up
map ctrl+shift+j	scroll_page_down

map ctrl+shift+plus	change_font_size all +2.0
map ctrl+shift+minus	change_font_size all -2.0

