# hyprpaper — configuración moderna

# Wallpaper para tu monitor principal
wallpaper {
    monitor = eDP-1
    path = /home/adriangln/Pictures/wallpapers/wall1.png
    fit_mode = cover
}

# Fallback (si no se aplica el de arriba)
wallpaper {
    monitor =
    path = /home/adriangln/Pictures/wallpapers/wall1.png
    fit_mode = cover
}
